name: Tests Workflow

on:
  push :
    branches:
      - main
      - release
      - develop
      - feat/tests
  pull_request: 
    branches:
      - main
      - release
      - develop
      - feat/tests

jobs: 
  test:
    runs-on: ubuntu-latest 
    env:
      FULL_NAME: "Гаенко Анастасия"
      GROUP_NUMBER: "M3110"

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Print information
        run: |
          echo "DO: ${{ env.FULL_NAME }}"
          echo "Номер группы: ${{ env.GROUP_NUMBER }}"
          echo "Ник на Github: ${{ github.actor }}"
        
      - name: Set up Python 3.13
        uses: actions/setup-python@v4 
        with:
          python-version: 3.13

      - name: Run unit tests
        run: |
          python -m unittest discover -s /home/runner/work/geometric_lib/geometric_lib/tests
      
      - name: Lint code with flake8
        run: |
          pip install flake8 autopep8
          autopep8 --in-place --aggressive --recursive .
          flake8 --ignore=F401 .
